### ISSUE TITLE
GPU memory usage and training time

### ISSUE THREAD

**Issue by zhaosonghui** [AlphaPlusTT/DAOcc#1]
This is an exciting study! I would like to ask how much memory each GPU uses in an 8-card 4090 setup, and approximately how long it takes for the model to converge when trained on 8 cards

**Comment by AlphaPlusTT** [comment]
Thank you for your interest! In our setup with 8 RTX 4090 GPUs, each GPU uses around 20GB of memory, and the training phase lasts for roughly 8 hours.

**Comment by zhaosonghui** [comment]
Thank you very much for your answer!
