### ISSUE TITLE
LiDAR sweeps

### ISSUE THREAD

**Issue by seamie6** [AlphaPlusTT/DAOcc#2]
Hello,
I am wondering how many LiDAR sweeps you utilise in your best-performing C+L model.

**Comment by AlphaPlusTT** [comment]
1+9

**Comment by AlphaPlusTT** [comment]
BTW, we uploaded a new version on arxiv, which contains all the relevant details of model training.

**Comment by AlphaPlusTT** [comment]
![2024-11-21 21-52-37屏幕截图](https://github.com/user-attachments/assets/af92b578-e110-4e34-9464-2cfb30deb88c)
