### ISSUE TITLE
About frames

### ISSUE THREAD

**Issue by MSunDYY** [AlphaPlusTT/DAOcc#4]
Excellent work! But I want to know how many frames of images and lidars do you use in your work?

**Comment by MSunDYY** [comment]
Yes,both image and lidar sweeps!

**Comment by AlphaPlusTT** [comment]
Zero, temporal information fusion, exponential moving average (EMA) for weight parameter and test-time augmentation is not used in all experiments.

**Comment by MSunDYY** [comment]
OK. Thank you very muach! Looking forward to your release!
